// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm6yxEqN3j0YD8nhByvfYiRx3wqeSolrs',
    appId: '1:963581436806:web:66a22f32e802fb97cec207',
    messagingSenderId: '963581436806',
    projectId: 'login-signup-64fe4',
    authDomain: 'login-signup-64fe4.firebaseapp.com',
    storageBucket: 'login-signup-64fe4.appspot.com',
    measurementId: 'G-XZPJB0R7GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYiqxDl0rcRvT3YrQH3cSAuZjokHmCRbM',
    appId: '1:963581436806:android:9b29988a3675c73dcec207',
    messagingSenderId: '963581436806',
    projectId: 'login-signup-64fe4',
    storageBucket: 'login-signup-64fe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYW2EBSfECwLAeVBkSzyOQDvmSLBnx5s',
    appId: '1:963581436806:ios:524988a400fbe542cec207',
    messagingSenderId: '963581436806',
    projectId: 'login-signup-64fe4',
    storageBucket: 'login-signup-64fe4.appspot.com',
    iosBundleId: 'com.example.signupform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQYW2EBSfECwLAeVBkSzyOQDvmSLBnx5s',
    appId: '1:963581436806:ios:81e55bd5d880136ecec207',
    messagingSenderId: '963581436806',
    projectId: 'login-signup-64fe4',
    storageBucket: 'login-signup-64fe4.appspot.com',
    iosBundleId: 'com.example.signupform.RunnerTests',
  );
}
